version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST: database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_survey
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - my-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=db_survey
    depends_on:
      - db
    networks:
      - my-network
    volumes:
      - .:/app
    command: npm run start

networks:
  my-network:
    driver: bridge

volumes:
  db: